# -*- coding: utf-8 -*-
"""track-phone-number-using-python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yc4f9tdOvcZaueNuXFhlPwhsoHkRCeAN
"""

pip install phonenumbers

import phonenumbers
from phonenumbers import geocoder
from phonenumbers import carrier

import folium

pip install opencage

from opencage.geocoder import OpenCageGeocode

number = input("Enter the phone number with country code : ")

phoneNumber = phonenumbers.parse(number)

Key= "7528fb797c254cb895c4c033d2787f85"

# printing the geolocation of the given number using the geocoder module
geolocation = geocoder.description_for_number(phoneNumber, "tr")
print("location : "+geolocation)

# printing the service provider name using the carrier module
service = carrier.name_for_number(phoneNumber,"en")
print("service provider : "+service)

from opencage.geocoder import OpenCageGeocode
geocoder = OpenCageGeocode(Key)
query =str("Turkey")
results = geocoder.geocode(query)
#print(results)

lat = results[0]['geometry']['lat']

long = results[0]['geometry']['lng']

print(lat, long)

# Assigning the latitude and longitude values to the lat and lng variables
lat = results[0]['geometry']['lat']
lng = results[0]['geometry']['lng']

# Getting the map for the given latitude and longitude
myMap = folium.Map(loction=[lat,lng],zoom_start = 9)

# Adding a Marker on the map to show the location name
folium.Marker([lat,lng],popup="Turkey").add_to(myMap)

# save map to html file to open it and see the actual location in map format
myMap.save("mylocation.html")

# track location and time zone using the phone number
import phonenumbers
from phonenumbers import timezone
from phonenumbers import geocoder
from phonenumbers import carrier

number = input("Enter the phone number with country code : ")
 
# Parsing String to the Phone number
phoneNumber = phonenumbers.parse(number)
 
# printing the timezone using the timezone module
timeZone = timezone.time_zones_for_number(phoneNumber)
print("timezone : "+str(timeZone))
 
# printing the geolocation of the given number using the geocoder module
geolocation = geocoder.description_for_number(phoneNumber,"en")
print("location : "+geolocation)
 
# printing the service provider name using the carrier module
service = carrier.name_for_number(phoneNumber,"en")
print("service provider : "+service)

